---
   - name: Install Java and other prerequisites
     apt:
       name:
         - default-jre
         - apt-transport-https
         - curl
         - software-properties-common
       state: present

   - name: Add Elasticsearch APT repository key
     apt_key:
       url: https://artifacts.elastic.co/GPG-KEY-elasticsearch

   - name: Add Elasticsearch APT repository
     apt_repository:
       repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
       state: present

   - name: Install Elasticsearch
     apt:
       name: elasticsearch
       state: present

   - name: Enable and start Elasticsearch service
     systemd:
       name: elasticsearch
       enabled: yes
       state: started

   - name: Install Kibana
     apt:
       name: kibana
       state: present

   - name: Enable and start Kibana service
     systemd:
       name: kibana
       enabled: yes
       state: started

   - name: Install Logstash
     apt:
       name: logstash
       state: present

   - name: Enable and start Logstash service
     systemd:
       name: logstash
       enabled: yes
       state: started

   - name: Restart Elasticsearch and Kibana
     systemd:
       name: "{{ item }}"
       state: restarted
     loop:
       - elasticsearch
       - kibana
